### ISSUE TITLE
copy edit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/cress-egg-heads#6]
Hi @lauraclay and @LornaLynch 
I've created a branch of this repo and made edits to worksheet.md
Old to new can be compared at - https://github.com/raspberrypilearning/cress-egg-heads/compare/update?expand=1
If you want to see the sheet in full it is at - https://github.com/raspberrypilearning/cress-egg-heads/blob/update/worksheet.md
Could I get a copy edit please, as I've made a few changes.

Cheers

**Comment by lauraclay** [comment]
All done - sorry for the delay, it's MagPi editing season!

**Comment by MarcScott** [comment]
Awesome - thanks
